[project]
name = "ten"
version = "1.0.0"
authors = [
  { name="Marc", email="mailnawman@gmail.com" },
]
description = "Tensor and mathematical library"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Linux",
]
license = "BSD-3-Clause"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/istmarc/tenpy"
Issues = "https://github.com/istmarc/ten"

